[models.gemini_1_5_flash_8b]
routing = ["google_ai_studio_gemini"]

[models.gemini_1_5_flash_8b.providers.google_ai_studio_gemini]
type = "google_ai_studio_gemini"
model_name = "gemini-1.5-flash-8b"

[functions.chatbot]
type = "chat"

# [functions.chatbot.variants.doctor]
# type = "chat_completion"
# weight = 0.5
# model = "gemini_1_5_flash_8b"

[functions.chatbot.variants.professional]
type = "chat_completion"
weight = 1
model = "gemini_1_5_flash_8b"


# [functions.chatbot.variants.kid]
# type = "chat_completion"
# weight = 0.8
# model = "gemini_1_5_flash_8b"
# temperature = 0.5
# Disable observability to keep this example minimal (not recommended in production)
[gateway]
disable_observability = true
